### ISSUE TITLE
Feedback on `AWS How to - CloudWatch monitoring scripts over HTTPS proxy on Ubuntu Linux (12.10 LTS)`

### ISSUE THREAD

**Issue by noxxi** [leonardinius/leonardinius.github.io#10]
`_posts/2015-01-08-CloudWatch-Monitoring-scripts.md`

----
Hi,
12.10 is not an LTS release, you probably mean 12.04.
And 12.04 comes with lwp-protocol-https 6.02 which defaults to use of IO::Socket::SSL instead of Crypt::SSLeay which you are trying to install. IO::Socket::SSL does a more correct checking of the certificate, supports SNI etc so it it preferred.
And finally, installing libnet-sslglue-perl and including it with 'use Net::SSLGlue::LWP' would give you proper proxy support without any extra hacks.

**Comment by leonardinius** [comment]
@noxxi Thanks, mis-typed. It obviously is.

I'll leave 12.04 LTS in the title and the text (however in the real life I've run ion on 12.10, but still - everything said/described should stay relevant, please correct if I'm wrong)

Will close the issue and make the changes, feel free to reopen as you see fit.
